 version: '3.8'
 services:
  ocpp-csms-bun:
   build: 
    context: .
    dockerfile: Dockerfile.local
   container_name:  ocpp-csms-bun
   ports: 
    - '3001:3001'
   volumes:
    - ./ocpp-csms-bun:/
    - /node_modules
